<?php

        return array (
  'default' => 
  array (
    'default_currency' => 'INR',
    'name' => 'FreeMoney',
    'copyright' => 
    array (
      'en' => 'copyright 2024',
      'hi' => 'copyright 2024 hi',
      'ja' => 'copyright 2024 ja',
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'default_lang' => 'en',
    'fallback_lang' => 'en',
    'default_country' => 'US',
    'timezone' => 'UTC',
    'admin_email' => 'freecash@givmail.com',
    'meta_info' => 1,
    'mailer' => 'smtp',
    'host' => 'sandbox.smtp.mailtrap.io',
    'port' => 2525,
    'username' => 'e67a67092dfe70',
    'password' => '1fe478b0209930',
    'encryption' => 'tls',
    'from_address' => 'freemon@getnada.com',
    'from_name' => 
    array (
      'en' => 'FreeCash',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'support_email' => 'freemon@getnada.com',
    'store_title' => 
    array (
      'en' => 'Assumenda aliquid an',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'store_desc' => 
    array (
      'en' => 'Commodi et totam est',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'store_h1' => 
    array (
      'en' => 'Quia consequatur Si',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'store_h2' => 
    array (
      'en' => 'Pariatur Laudantium',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'deal_title' => 
    array (
      'en' => 'Dolore tempor quisqu',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'deal_desc' => 
    array (
      'en' => 'Iste beatae ipsam te',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'deal_h1' => 
    array (
      'en' => 'Temporibus in quia r',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'deal_h2' => 
    array (
      'en' => 'Ratione harum deseru',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'page_title' => 
    array (
      'en' => 'Fugiat velit fugiat',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'page_desc' => 
    array (
      'en' => 'Iure in pariatur Mi',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'page_h1' => 
    array (
      'en' => 'Eaque laborum conseq',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'page_h2' => 
    array (
      'en' => 'Sapiente in eos ape',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'coupon_category_title' => 
    array (
      'en' => 'Ut exercitationem qu',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'coupon_category_desc' => 
    array (
      'en' => 'Consectetur odio adi',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'coupon_category_h1' => 
    array (
      'en' => 'Et maxime exercitati',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'coupon_category_h2' => 
    array (
      'en' => 'Impedit in ad itaqu',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'store_category_title' => 
    array (
      'en' => 'Ducimus ex tenetur',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'store_category_desc' => 
    array (
      'en' => 'Obcaecati inventore',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'store_category_h1' => 
    array (
      'en' => 'Quam magni ut dolore',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'store_category_h2' => 
    array (
      'en' => 'Quis incididunt quib',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'deal_category_title' => 
    array (
      'en' => 'Impedit non veniam',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'deal_category_desc' => 
    array (
      'en' => 'Amet animi invento',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'deal_category_h1' => 
    array (
      'en' => 'Amet totam esse ei',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'deal_category_h2' => 
    array (
      'en' => 'Sunt incidunt occae',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'listing_title' => 
    array (
      'en' => 'Voluptas odio rerum',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'listing_desc' => 
    array (
      'en' => 'Deleniti repellendus',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'listing_h1' => 
    array (
      'en' => 'Cum eligendi dolore',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'listing_h2' => 
    array (
      'en' => 'Qui quos ut ipsum c',
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'robots' => 'Illo ipsum illo sit',
    'gift_card_api_url' => 'Cupiditate esse tem',
    'gift_card_api_key' => 'Placeat animi haru',
    'gift_card_api_secret' => 'Est et et id volupta',
    'gift_card_from_email' => 'farodohur@mailinator.com',
    'gift_card_from_name' => 'Thaddeus Howell',
    'facebook' => 'Harum sit aut totam',
    'twitter' => 'Ea reprehenderit rep',
    'youtube' => 'Culpa esse aliquid',
    'instagram' => 'Harum porro voluptat',
    'telegram' => 'Praesentium harum un',
    'pinterest' => 'Cumque et sed tempor',
    'whatsapp' => 'Voluptatem dicta deb',
    'reddit' => 'Est consequatur dol',
    'discord' => 'Nulla dolor sed dolo',
    'linkdin' => 'Reprehenderit culpa',
    'app_ios' => 'Harum modi nulla non',
    'app_android' => 'Officiis sit soluta',
    'extn_safari' => 'Adipisci dolorum har',
    'extn_edge' => 'Possimus dolorem ad',
    'extn_firefox' => 'Reprehenderit culpa',
    'extn_chrome' => 'Voluptas do eaque si',
    'recaptcha_key' => '6Ld42uUpAAAAAPHLhM5JwVbu9Luz2GlNAIaQqs-g',
    'recaptcha_secret' => '6Ld42uUpAAAAAPAJjBbVQxUytQUf-XfWBmUZroNv',
    'google_translate_apikey' => 'Est mollitia cupidit',
    'google_client_id' => 'Id facere deleniti',
    'google_client_secret' => 'Consequat Iure fugi',
    'facebook_client_id' => 'Nostrud sunt saepe',
    'facebook_client_secret' => 'Ab distinctio Dolor',
    'apple_client_id' => 'Quo quo adipisci qua',
    'apple_client_secret' => 'Ut omnis qui sapient',
    'unstoppable_domains_client_id' => 'Deserunt consequat',
    'unstoppable_domains_client_secret' => 'Quis qui mollitia ei',
    'sms_sender_id' => 'Et id fugiat quas mo',
    'sms_api_url' => 'Non qui iure tenetur',
    'mailchimp_api_key' => 'Sunt excepturi et n',
    'mailchimp_guest_list_id' => 'Et aliqua Molestiae',
    'mailchimp_user_list_id' => 'Iure veniam quidem',
    'mailchimp_double_option' => 'subscribed',
    'onesignal_app_id' => NULL,
    'onesignal_rest_api' => NULL,
    'onesignal_user_auth_key' => NULL,
    'telegram_boat_token' => NULL,
    'telegram_user_id' => NULL,
    'crypto_rate_api_key' => NULL,
    'crypto_currencies' => NULL,
    'exchange_rate_api_key' => NULL,
    'twitter_api_key' => NULL,
    'twitter_api_secret' => NULL,
    'twitter_api_token' => NULL,
    'gift_card_countries' => NULL,
    'google_maps_api_key' => NULL,
    'default_user_percent' => 0,
    'default_gift_card_cashback_percent' => 0,
    'out_seconds' => 0,
    'header_cache_seconds' => 21600,
    'referral_enabled' => 1,
    'referral_percent' => 5,
    'claim_min_days' => 1,
    'claim_max_days' => 10,
    'should_verify_phone' => 1,
    'otp_message' => 
    array (
      'en' => NULL,
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'otp_wait_seconds' => 45,
    'max_phone_length' => 15,
    'cashback_sentence' => 
    array (
      'en' => NULL,
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'reward_sentence' => 
    array (
      'en' => NULL,
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'withdrawal_subject' => 
    array (
      'en' => NULL,
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'withdrawal_message' => 
    array (
      'en' => NULL,
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'code_head' => NULL,
    'code_foot' => NULL,
    'code_body' => NULL,
    'asset_version' => NULL,
    'affport_download' => 0,
    'extension_google_serp' => NULL,
    'aff_link_params' => NULL,
    'twitter_pagination_token' => NULL,
    'extension_exclude_domain' => NULL,
    'color_primary' => '#6423d2',
    'color_secondary' => '#ff790e',
    'color_body_bg' => '#fdf8f3',
    'color_body_text' => '#12253b',
    'color_border' => '#dec8ed',
    'footer_bg_color' => '#fcf0e2',
    'footer_link_title_color' => '#12253b',
    'footer_link_color' => '#b2b4bb',
    'input_bg_color' => '#f5f5f5',
    'deal_style' => 1,
    'container_width' => '1320px',
    'font_code' => NULL,
    'similar_store_count' => 4,
    'footer_columns_count' => 6,
    'cta_enabled' => 1,
    'location' => 'footer',
    'bg_color' => '#6423d2',
    'bg_transparent' => 0,
    'content' => 
    array (
      'en' => NULL,
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'ai_cta_enabled' => 1,
    'ai_location' => 'footer',
    'ai_bg_color' => '#ffffff',
    'ai_content' => 
    array (
      'en' => NULL,
      'hi' => NULL,
      'ja' => NULL,
      'gu' => NULL,
      'fr' => NULL,
      'mara' => NULL,
    ),
    'logo' => 'vdarHD0SNTplflCUHlx6OKO3uE0NCz0aZu8FPJHn.png',
    'favicon' => 'settings/31gzvjK25gzkWdNWJWCvI4K3nDJtYZLz3yzx6qmA.png',
    'point_conversion_rate' => 1000,
  ),
  'lang' => 
  array (
    'all' => 
    array (
      'en' => 'English',
      'hi' => 'hindi',
      'ja' => 'japanese ',
      'gu' => 'gujarati',
      'fr' => 'franch',
      'mara' => 'marathi',
    ),
    'keys' => 
    array (
      0 => 'en',
      1 => 'hi',
      2 => 'ja',
      3 => 'gu',
      4 => 'fr',
      5 => 'mara',
    ),
    'default' => 'en',
  ),
  'countries' => 
  array (
    'all' => 
    array (
      'AF' => 
      array (
        'id' => 1,
        'name' => 'Afghanistan',
        'code' => 'AF',
        'is_enabled' => 1,
        'default_language' => 'en',
        'languages' => '["en","ms","gu"]',
        'currency' => 'AUD',
        'created_at' => NULL,
        'updated_at' => NULL,
        'dial_code' => '+93',
      ),
      'AX' => 
      array (
        'id' => 2,
        'name' => 'Åland Islands',
        'code' => 'AX',
        'is_enabled' => 1,
        'default_language' => 'en',
        'languages' => '["en","ms","hi"]',
        'currency' => 'USD',
        'created_at' => NULL,
        'updated_at' => NULL,
        'dial_code' => '+358',
      ),
      'AU' => 
      array (
        'id' => 14,
        'name' => 'Australia',
        'code' => 'AU',
        'is_enabled' => 1,
        'default_language' => 'en',
        'languages' => '["en","ja"]',
        'currency' => 'AUD',
        'created_at' => NULL,
        'updated_at' => NULL,
        'dial_code' => '+61',
      ),
      'IN' => 
      array (
        'id' => 103,
        'name' => 'India',
        'code' => 'IN',
        'is_enabled' => 1,
        'default_language' => 'en',
        'languages' => '["hi","en"]',
        'currency' => 'INR',
        'created_at' => NULL,
        'updated_at' => NULL,
        'dial_code' => '+91',
      ),
      'JP' => 
      array (
        'id' => 112,
        'name' => 'Japan',
        'code' => 'JP',
        'is_enabled' => 1,
        'default_language' => 'en',
        'languages' => '["en","ja"]',
        'currency' => 'JPY',
        'created_at' => NULL,
        'updated_at' => NULL,
        'dial_code' => '+81',
      ),
      'MY' => 
      array (
        'id' => 135,
        'name' => 'Malaysia',
        'code' => 'MY',
        'is_enabled' => 1,
        'default_language' => 'ms',
        'languages' => '["en","ms"]',
        'currency' => 'MYR',
        'created_at' => NULL,
        'updated_at' => NULL,
        'dial_code' => '+60',
      ),
      'MV' => 
      array (
        'id' => 136,
        'name' => 'Maldives',
        'code' => 'MV',
        'is_enabled' => 1,
        'default_language' => '',
        'languages' => '[]',
        'currency' => 'MVR',
        'created_at' => NULL,
        'updated_at' => NULL,
        'dial_code' => '+960',
      ),
      'US' => 
      array (
        'id' => 236,
        'name' => 'United States',
        'code' => 'US',
        'is_enabled' => 1,
        'default_language' => '',
        'languages' => '["ms","en"]',
        'currency' => 'USD',
        'created_at' => NULL,
        'updated_at' => NULL,
        'dial_code' => '+1',
      ),
    ),
    'keys' => 
    array (
      0 => 'AF',
      1 => 'AX',
      2 => 'AU',
      3 => 'IN',
      4 => 'JP',
      5 => 'MY',
      6 => 'MV',
      7 => 'US',
    ),
  ),
  'currencies' => 
  array (
    'all' => 
    array (
      'INR' => 
      array (
        'id' => 2,
        'name' => 'Indian rupees',
        'iso_code' => 'INR',
        'symbol' => '₹',
        'symbol_position' => 'prefix',
        'enabled' => 1,
        'created_at' => '2024-05-30T10:37:17.000000Z',
        'updated_at' => '2024-05-30T10:38:07.000000Z',
      ),
      'USD' => 
      array (
        'id' => 10,
        'name' => 'US dollars',
        'iso_code' => 'USD',
        'symbol' => '$',
        'symbol_position' => 'prefix',
        'enabled' => 1,
        'created_at' => '2024-06-10T06:50:16.000000Z',
        'updated_at' => '2024-07-11T11:35:09.000000Z',
      ),
    ),
    'keys' => 
    array (
      0 => 'INR',
      1 => 'USD',
    ),
    'default' => 
    array (
    ),
  ),
) ; ?>