export const atomKey = {
  settings: 'settings',
  settings_loading: 'settings_loading',
  is_signin_pop_up_visible: 'is_signin_pop_up_visible',
  is_signup_pop_up_visible: 'is_signup_pop_up_visible',
  publicData: {
    activeSidebarRoute: 'activeSidebarRoute',
    offers_task: 'offers_task',
    offers_task_loading: 'offers_task_loading',
    category_list: 'category_list',
    category_list_loading: 'category_list_loading',
    category_filter: 'category_filter',
    survey_provider_list: 'survey_provider_lits',
    survey_provider_list_loading: 'survey_provider_lits_loading',
    task_provider_list: 'task_provider_list',
    task_provider_list_loading: 'task_provider_list_loading',
    single_category_offer_task: 'single_category_offer_task',
  },
  translation: {
    currentSelectedLanguage: 'currentSelectedLanguage',
  },
  previousUrl: 'previousUrl',
  chatRooms: 'chatRooms',
  ProfileVerifyValue: 'ProfileVerifyValue',
  ProfileEmailValue: 'ProfileEmailValue',
  validPhoneNumber: 'validPhoneNumber',
  roomCounts: 'roomCounts',
  surveyProviderList: 'surveyProviderList',
  taskProviderList: 'taskProviderList',
  activeTaskProviderList: 'activeTaskProviderList',
  isConnected: 'isConnected',
  claim_store_list: 'claim_store_list',
  footer_content: 'footer_content',
  toggleChatSidebar: 'toggleChatSidebar',
  chatMentionCounter: 'chatMentionCounter',
  notificationMentionCounter: 'notificationMentionCounter',
};
