import { config } from '@/config';
import { AppRoutes } from '@/routes-config';
import { GlobeAmericasIcon } from '@heroicons/react/24/solid';
import { useSession } from 'next-auth/react';
import Image from 'next/image';
import { useTranslation } from 'react-i18next';
import { SvgAndroid, SvgApple, SvgDesktop } from '@/components/Generic/Icons';

const useConstant = () => {
  const { t } = useTranslation();
  let regionNames = new Intl.DisplayNames(['en'], { type: 'region' });
  const { data, status }: any = useSession();

  const TickerCountryDropDown = [
    {
      key: 'globe',
      label: t('globe'),
      image: <GlobeAmericasIcon className="flex-shrink-0 size-5" />,
    },
    {
      key: status == 'authenticated' ? data?.user?.user?.country_code : 'IN',
      label:
        status == 'authenticated'
          ? data?.user?.user?.country_code
            ? regionNames.of(data?.user?.user?.country_code)
            : regionNames.of('IN')
          : 'IN',
      image: (
        <div className="flex-shrink-0 size-5 rounded-full overflow-hidden">
          {data?.user?.user?.country_code ? (
            <Image
              className="h-full w-full object-cover"
              // src={config.COUNTRY_FLAG?.replace(':COUNTRY_CODE', userInfo?.country_code?.toLowerCase())}
              src={config.COUNTRY_FLAG?.replace(
                ':COUNTRY_CODE',
                status == 'authenticated' ? data?.user?.user?.country_code?.toLowerCase() : 'in'
              )}
              alt="country-icon"
              width={30}
              height={30}
            />
          ) : null}
        </div>
      ),
    },
  ];

  const EarningSubMenu = [
    {
      id: 1,
      name: 'my_earning',
      route: AppRoutes.overviewEarning,
    },
    {
      id: 2,
      name: 'withdrawal',
      route: AppRoutes.overviewWithdrawal,
    },
    {
      id: 3,
      name: 'ongoing-offer',
      route: AppRoutes.overviewOngoingOffer,
    },
    {
      id: 4,
      name: 'charge-back',
      route: AppRoutes.overviewChargeBack,
    },
    {
      id: 5,
      name: 'missing_claims',
      route: AppRoutes.overviewMissingClaim,
    },
    {
      id: 6,
      name: 'clicks',
      route: AppRoutes.overviewClicksClaim,
    },
  ];

  // offer radio filter device options
  const deviceFilterOptions = [
    { key: 'all', label: t('all'), icon: null },
    { key: config.IOS_KEY, label: t('filter_ios'), icon: <SvgApple className="size-4" /> },
    { key: config.ANDROID_KEY, label: t('filter_android'), icon: <SvgAndroid className="size-4" /> },
    { key: config.DESKTOP_KEY, label: t('filter_desktop'), icon: <SvgDesktop className="size-4" /> },
  ];

  // dummy data remove this once dynamic
  const storeCardData = [
    {
      name: '100percentpure DE/AT',
      about:
        '<p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><strong style="margin: 0px; padding: 0px;">Wer sind wir?</strong></p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">100% Pure Naturkosmetik<br style="margin: 0px; padding: 0px;">Die Kult Naturkosmetik aus Kalifornien jetzt auch in Europa!<br style="margin: 0px; padding: 0px;">Profitieren Sie von einer der größten Naturkosmetik Marken in den USA!</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Die neue Kult Marke, von den Mega Stars aus Amerika gefeiert!</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">100% Pure Naturkosmetik!</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><strong style="margin: 0px; padding: 0px;">Einige Fakten zu den Produkten von Pure:</strong></p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Gewonnen aus natürlichen Inhaltsstoffen,</p><ul style="margin-right: 0px; margin-left: 0px; padding-left: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">OHNE synthetische Chemikalien</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">OHNE künstliche Duftstoffe</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">OHNE petrochemische Substanzen</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">OHNE chemische Konservierungsstoffe</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">OHNE künstliche Farbstoffe</li></ul><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Unsere Produkte sind so pur, rein und in jeder Hinsicht unschädlich, dass man sie sogar essen kann.<br style="margin: 0px; padding: 0px;">Ein wahrer Durchbruch in der Beauty Industrie, sind die 100% Pure Make-up Produkte.<br style="margin: 0px; padding: 0px;">Gefärbt mit Farbpigmenten aus Früchten ist 100% Pure die erste und einzige dekorative Kosmetik, die ihre Färbung ausschließlich durch Frucht- und Gemüsepigmente erhält.</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 148,
      slug: '100percentpure-deat',
      logo: 'https://savebucks.de/img/100percentpure-deat.png',
      banner_image: 'https://savebucks.de/img/categories/shutterstock-1680951871.jpeg',
      homepage: 'https://www.100percentpure.de',
      domain_name: '100percentpure.de',
      extension_afflink: null,
      cats: ['10', '13', '11', '9'],
      cashback_enabled: 1,
      cashback_amount: '10.50',
      cashback_type: 'cashback',
      cashback_was: 'percent|7.50',
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 105,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 478,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-000-0000010.50',
      similar_stores: [],
      cashback_string: 'Bis zu 10.5% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Weitere Geschenkartikel', 'Beauty & Gesundheit', 'Make Up & Parfum', 'Gesundheit'],
    },
    {
      name: '12-Travel',
      about:
        '<p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">12-Travel.de ist ein kompetenter Reisevermittler, der mit über 140 Reiseveranstaltern zusammenarbeitet. 12-Travel sucht und findet für alle Kunden aus dem unübersichtlichen und schier unendlichen Angeboten der Reiseveranstalter, garantiert das individuell am besten zu Ihnen passende Angebot für Ihren Traumurlaub. Und das alles selbstverständlich zu einem sensationell niedrigen Preis.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">12-Travel findet absolut zuverlässig die perfekte Traumreise!</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 276,
      slug: '12-travel',
      logo: 'https://savebucks.de/img/12-travel-de.png',
      banner_image: null,
      homepage: 'https://www.12-travel.de',
      domain_name: '12-travel.de',
      extension_afflink: null,
      cats: ['1', '3'],
      cashback_enabled: 1,
      cashback_amount: '2.80',
      cashback_type: 'cashback',
      cashback_was: 'percent|2.00',
      amount_type: 'percent',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 107,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 486,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-000-0000002.80',
      similar_stores: [],
      cashback_string: 'Bis zu 2.8% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Freizeit & Reisen', 'Reisen'],
    },
    {
      name: '123Blumenversand',
      about:
        '<p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><strong style="margin: 0px; padding: 0px;"><u style="margin: 0px; padding: 0px;">Blumen verschicken mit 123Blumenversand</u></strong></p><p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">123Blumenversand bietet tolle Blumensträuße mit 7-Tage-Frischegarantie zu attraktiven Preisen.</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 3911,
      slug: '123blumenversand',
      logo: 'https://savebucks.de/img/images/partner-logos/16023.png',
      banner_image: null,
      homepage: 'http://www.123blumenversand.de',
      domain_name: '123blumenversand.de',
      extension_afflink: null,
      cats: ['6', '9'],
      cashback_enabled: 1,
      cashback_amount: '14.00',
      cashback_type: 'cashback',
      cashback_was: 'percent|10.00',
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 29,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 429,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-000-0000014.00',
      similar_stores: [],
      cashback_string: 'Bis zu 14% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Geschenke & Bücher', 'Weitere Geschenkartikel'],
    },
    {
      name: '1822direkt',
      about:
        '<p><span style="caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Die 1822direkt ist eine 100%ige Tochter der Frankfurter Sparkasse, der viertgrößten Sparkasse in Deutschland. Seit dem 28. September 1996 ist die 1822direkt im Direktbanking tätig und versteht sich als Universalanbieter für den Privatkundenbereich.</span><br></p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 1120,
      slug: '1822direkt',
      logo: 'https://savebucks.de/img/1822direkt-gesellschaft-der-frankfurter-sparkasse.png',
      banner_image: null,
      homepage: 'https://www.1822direkt.com',
      domain_name: '1822direkt.com',
      extension_afflink: null,
      cats: ['36', '38', '102'],
      cashback_enabled: 1,
      cashback_amount: '56.00',
      cashback_type: 'cashback',
      cashback_was: 'fixed|40.00',
      amount_type: 'fixed',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 88,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 482,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-999-0000056.00',
      similar_stores: [],
      cashback_string: 'Bis zu 56,00 € Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Finanzen & Versicherungen', 'Banken', 'Kredite'],
    },
    {
      name: '1a-Geschenkeshop',
      about:
        '<p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">1a-Geschenkeshop hat sich auf persönliche, individuelle Geschenke spezialisiert. Fast jedes Produkt wird mit Namen, Wunschtext, Foto oder anderen individuellen Kundenwünschen ein ganz einzigartiges Geschenk.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Die Geschenke sind sortiert nach Anlasse, Berufe oder Hobby. Besonders beliebt sind die Schraubenmännchen mit Schild. Die Schraubenmännchen werden von den Kunden nach Beruf oder Hobby des Beschenkten ausgewählt. Ein Schild mit einer persönlichen Widmung bietet die Möglichkeit, aus diesen Produkten ein ganz individuelles Geschenk zu machen.</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 716,
      slug: '1a-geschenkeshop',
      logo: 'https://savebucks.de/img/1a-geschenkeshop-de.png',
      banner_image: null,
      homepage: 'https://www.1a-geschenkeshop.de',
      domain_name: '1a-geschenkeshop.de',
      extension_afflink: null,
      cats: ['6', '9'],
      cashback_enabled: 1,
      cashback_amount: '7.00',
      cashback_type: 'cashback',
      cashback_was: 'percent|5.00',
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 39,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 431,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-000-0000007.00',
      similar_stores: [],
      cashback_string: 'Bis zu 7% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Geschenke & Bücher', 'Weitere Geschenkartikel'],
    },
    {
      name: '1blu',
      about:
        '<p><span style="caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Die Berliner 1blu AG bietet moderne, preiswerte Webhosting-Lösungen für professionelle Internetpräsenzen.&nbsp; Das Sortiment umfasst Webhosting-Pakete, virtuelle, dedizierte und Managed Server sowie Domains zu besonders attraktiven Preisen. Mit zahlreichen Produktinnovationen für Einsteiger und Profis trägt 1blu dazu bei, Webhosting komfortabler, einfacher und spannender zu machen. Die 1blu-Gruppe zählt mit 300.000 Kundenverträgen zu den größten Webhosting-Unternehmen in Deutschland.</span><br></p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 284,
      slug: '1blu-de',
      logo: 'https://savebucks.de/img/1blu-de.png',
      banner_image: null,
      homepage: 'https://www.1blu.de',
      domain_name: '1blu.de',
      extension_afflink: null,
      cats: ['29', '37'],
      cashback_enabled: 1,
      cashback_amount: '63.00',
      cashback_type: 'cashback',
      cashback_was: 'fixed|45.00',
      amount_type: 'fixed',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 83,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 462,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-999-0000063.00',
      similar_stores: [],
      cashback_string: 'Bis zu 63,00 € Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Internet & Telefon', 'Sonstiges'],
    },
    {
      name: '2Ocean',
      about:
        '<p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Wir leben das Thema Elektromobilität und das seit Jahren. Dies zeigt sich nicht nur anhand unserer langjährigen Erfahrung im Bereich elektrifizierter Mobilitätslösungen, sondern auch an der Begeisterung, die unser Team vereint.</p><ul style="margin-right: 0px; margin-left: 0px; padding-left: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Von der digitalen Verarbeitung bis zur ganzheitlichen Vermarktung der THG-Quote.</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">2Ocean ist ein Prämienauszahler für die THG-Quote für private E-Fahrzeug Fahrer, Flottenbetreiber &amp; Großkunden.</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Aufgrund einer neuen EU Richtlinie, die am 01. Januar 2022 in Deutschland in Kraft getreten ist, sind je Fahrzeug mehrere Hundert Euro jedes Jahr aufs Neue möglich.</li></ul><p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">&nbsp;</p><p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><strong style="margin: 0px; padding: 0px;">Unsere Vision |&nbsp;Eine faire Emissionsverteilung zur Beschleunigung der Elektromobilität.</strong></p><p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Die Zukunft der Mobilität ist elektrisch. Doch das funktioniert nur, wenn klassische Akteure im Bereich automotive ganzheitlich an der Umstellung mitwirken. Wir helfen dabei, dass Erlöse aus dem Verkauf von CO2-Emissionszertifikaten in nur wenigen Schritten bei den Verbrauchern landen und haben die Herausforderung einer fairen Energieverteilung und nachhaltigen Mobilitätswende angenommen!</p><p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">&nbsp;</p><p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><strong style="margin: 0px; padding: 0px;">Die Idee | Eine Plattform für Dich.</strong></p><p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">In 2021 wurde ein Gesetzesentwurf verabschiedet, welcher dabei hilft, genau diese Energieverteilung analog des Ausstoßes durchzusetzen. Im Grunde hat der Gesetzesgeber ein Instrument geschaffen, was die Basis für einen nachhaltigen Aufbau der Elektromobilität ermöglicht. Die Mobilitätswende soll somit nicht nur aus Steuergeldern finanziert werden. Stattdessen werden auch direkt Gelder von Ölkonzernen mit entsprechend hohem CO2 Ausstoß in neue Technologien umverteilt. Elektroautos werden durch diese Regelung mit einer pauschalen Menge an CO2-Einsparungen zertifiziert, jedes Jahr aufs Neue. Öl-Konzerne haben nun die Möglichkeit, die CO2 Werte ihrer Treibstoffe genau mit diesen Zertifikaten auszugleichen. Da es als einzelner Halter eines Elekteoautos allerdings nahezu unmöglich ist, an diese Konzerne das eigene Zertifikat zu verkaufen, haben wir wirkaufendeinzertifikat.de gegründet. Wir kümmern uns um die zeitintensive Zertifizierung der Fahrzeugs beim Umweltbundesamt, übernehmen die Abstimmung mit dem Zoll und bündeln anschließend die Zertifikate in eine Mindestabnahmemenge, um sie von unseren Brokern an die Mineralölkonzerne zu vermarkten.</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 3719,
      slug: '2ocean',
      logo: 'https://savebucks.de/img/2ocean-de.png',
      banner_image: null,
      homepage: 'https://2ocean.de',
      domain_name: '2ocean.de',
      extension_afflink: null,
      cats: ['37'],
      cashback_enabled: 1,
      cashback_amount: '21.00',
      cashback_type: 'cashback',
      cashback_was: 'fixed|15.00',
      amount_type: 'fixed',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 67,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 16,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-999-0000021.00',
      similar_stores: [],
      cashback_string: 'Bis zu 21,00 € Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Sonstiges'],
    },
    {
      name: '3D Kennzeichen',
      about:
        '<div class="wpb_text_column wpb_content_element " style="caret-color: rgb(85, 85, 85); color: rgb(85, 85, 85); font-family: Lato, Arial, Helvetica, sans-serif; font-size: 14px; text-align: justify;"><div class="wpb_wrapper"><p>Die 3D-Kennzeichen GmbH stellt seit 2013 Kunststoff-KFZ-Kennzeichen und Zubehör mit Premiumwerkstoffen her und setzt so im Bereich der Autokennzeichen neue Qualitätsstandards. Das Unternehmen sitzt in der niederbayerischen Dreiflüssestadt Passau und ist nicht nur alleiniger Hersteller, sondern auch Patentinhaber der 3D Kennzeichen. Alle im Internet erhältlichen 3D Kennzeichen stammen aus der Produktion der 3D-Kennzeichen GmbH.</p></div></div><div class="wpb_text_column wpb_content_element " style="caret-color: rgb(85, 85, 85); color: rgb(85, 85, 85); font-family: Lato, Arial, Helvetica, sans-serif; font-size: 14px; text-align: justify;"><div class="wpb_wrapper"><p>Im Jahr 2011 entwickelte der Erfinder Dr. Michael Bauer die Grundidee für KFZ-Kennzeichen aus hochwertigem und robustem Kunststoff. Nach dreijähriger Entwicklungszeit sind die 3D Kennzeichen seit Herbst 2013 erhältlich. Mit einzeln aufgesetzten, präzise geformten 3D Lettern wirkt das neue Kennzeichen dreidimensionaler als die schwächer definierte Prägung herkömmlicher Blechschilder: So entstand der Name 3D Kennzeichen.</p></div></div>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 494,
      slug: '3d-kennzeichen',
      logo: 'https://savebucks.de/img/3d-kennzeichen.png',
      banner_image: null,
      homepage: 'https://3d-kennzeichen.de',
      domain_name: '3d-kennzeichen.de',
      extension_afflink: null,
      cats: ['4'],
      cashback_enabled: 1,
      cashback_amount: '70.00',
      cashback_type: 'cashback',
      cashback_was: 'percent|50.00',
      amount_type: 'percent',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 37,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 429,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-000-0000070.00',
      similar_stores: [],
      cashback_string: 'Bis zu 70% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Auto'],
    },
    {
      name: '8wines',
      about:
        '<p><span style="caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Die Menschen in Deutschland, Österreich und der Schweiz trinken gerne Wein und wir bieten ihnen eine sehr große Auswahl zum bestmöglichen Preis an. Bereits das fünfte Jahr in Folge haben wir die Ehre, mit den goldenen Medaillen vom Wine-Searcher für unsere erlesene Weinauswahl ausgezeichnet zu werden. Im Vergleich zur Konkurrenz bieten wir Premium-Weine an, die aus der ganzen Welt importiert werden und in der DACH-Region nur schwer zu finden sind, was für uns einen großen Vorteil und für unsere Kunden einen hervorragenden Wert darstellt.&nbsp;</span><br style="margin: 0px; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><span style="caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Unser Lager befindet sich in Prag und die Lieferung ist sehr schnell und sicher.&nbsp;</span><br></p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 788,
      slug: '8wines',
      logo: 'https://savebucks.de/img/8wines-dach.png',
      banner_image: null,
      homepage: 'https://8wines.de',
      domain_name: '8wines.de',
      extension_afflink: null,
      cats: ['14', '16'],
      cashback_enabled: 1,
      cashback_amount: '4.20',
      cashback_type: 'cashback',
      cashback_was: 'percent|5.60',
      amount_type: 'percent',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 41,
      offers_count: 2,
      rating: '0.0',
      rating_count: 0,
      clicks: 30,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: '0-9',
      cashback_sort: '999-000-0000004.20',
      similar_stores: [],
      cashback_string: 'Bis zu 4.2% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Essen & Trinken', 'Alkoholische Getränke'],
    },
    {
      name: 'a&o FEEL THE LIFE',
      about:
        '<span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">A&amp;O FEEL THE LIFE</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">Wir produzieren ausschließlich hochwertige Haarpflege- und Stylingprodukte. Dabei verzichten wir auf alle bedenklichen und unerforschten Inhaltsstoffe. a&amp;o Produkte sind PETA-zertifiziert, vegan, silikon-, paraben-, sulfat- und mineralölfrei sowie ohne Tierversuche hergestellt.</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">WHO WE ARE</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">Wir sind Ali und Toby. Mit 15 Jahren fanden wir unseren Weg und sind als Hairdresser druchgestartet. Wir strebten schon als Lehrlinge danach, besser als unsere Meister zu sein und lernten uns schließlich als junge Hairdresser in einem der weltweit größten Stylistenhäuser kennen.</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">Seitdem streben wir gemeinsam nach dem Einklang zwischen gesundem Haar, seiner perfekten Form und dem Menschen in seiner Individualität.</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">OUR PHILOSOPHY</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">Auf unserem Weg ist uns bewusst geworden, dass es uns nicht darauf ankommt, wie viele Produkte wir verwenden, sondern welche und in welcher Kombination. Seit dem Jahr 2014 entwickeln wir mit all unserem Wissen, leidenschaftlich Haarpflege für Menschen, die diese Philosophie mit uns teilen. Dabei fokussieren wir uns auf das, was drin ist und geben dir maximale Transparenz.</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">THE A&amp;O</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><span style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">Der Name a&amp;o wurde von dem deutschen Designer Peter Schmidt kreiert. Peter Schmidt wurde 1937 in Bayreuth geboren. Er prägte Marken wie JIL SANDER, HUGO BOSS, JOOP und Marlies Möller mit seinen Logodesigns.</span><br style="caret-color: rgb(40, 60, 67); color: rgb(40, 60, 67); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 504,
      slug: 'ao-feel-the-life',
      logo: 'https://savebucks.de/img/ao-feel-the-life.jpg',
      banner_image: null,
      homepage: 'https://www.aundo-products.de',
      domain_name: 'aundo-products.de',
      extension_afflink: null,
      cats: ['10'],
      cashback_enabled: 1,
      cashback_amount: '7.50',
      cashback_type: 'cashback',
      cashback_was: 'percent|50.00',
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 20,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 16,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-000-0000007.50',
      similar_stores: [],
      cashback_string: 'Bis zu 7.5% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Beauty & Gesundheit'],
    },
    {
      name: 'Aarniwood',
      about:
        '<p><span style="caret-color: rgb(52, 52, 52); color: rgb(52, 52, 52); font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; white-space: pre-wrap;">Aarniwood ist eine finnische Marke, die Holzuhren und Sonnenbrillen sowie Ledertaschen und Geldbörsen verkauft.\r\n\r\nAarni ist ein finnisches Wort für wilden, ungezähmten Wald, der von Menschenhand unberührt bleibt, was die Geschichte ihrer Produkte ist. Aarniwood verwendet nur die besten Materialien direkt aus der Natur und kombiniert das elegante Design mit natürlichen Materialien.\r\n\r\nBei Aarniwood konzentrieren sie sich auf die Umwelt und verbringen mehrere Monate damit, ihre Produkte zu entwerfen, wobei sie sich nur auf die besten verfügbaren Materialien, Komponenten und Handwerkskunst verlassen. Und jedes einzelne Stück Holz in den Produkten ist zertifiziert.</span><br></p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 3783,
      slug: 'aarniwood',
      logo: 'https://savebucks.de/img/aarniwood.',
      banner_image: null,
      homepage: 'https://aarniwood.com',
      domain_name: 'aarniwood.com',
      extension_afflink: null,
      cats: ['20', '23'],
      cashback_enabled: 1,
      cashback_amount: '4.90',
      cashback_type: 'cashback',
      cashback_was: 'percent|3.50',
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 15,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 427,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-000-0000004.90',
      similar_stores: [],
      cashback_string: 'Bis zu 4.9% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Kleidung & Mode', 'Schmuck & Accessoires'],
    },
    {
      name: 'Abonauten Genuss-Abo',
      about:
        '<p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Im Abonauten Genuss-Abo kann man derzeit monatlich erhalten:</p><ul style="margin-right: 0px; margin-left: 0px; padding-left: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Gin</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Champagner</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Wein</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Whisky</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Espresso</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Filterkaffee</li><li style="margin: 0px; padding: 0px; list-style-position: inside; list-style-type: disc;">Käse</li></ul>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 335,
      slug: 'abonauten-genuss-abo-de',
      logo: 'https://savebucks.de/img/images/partner-logos/22657png.jpeg',
      banner_image: null,
      homepage: 'https://abonauten.de',
      domain_name: 'abonauten.de',
      extension_afflink: null,
      cats: ['16'],
      cashback_enabled: 1,
      cashback_amount: '7.00',
      cashback_type: 'cashback',
      cashback_was: 'percent|5.00',
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 18,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 17,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-000-0000007.00',
      similar_stores: [],
      cashback_string: 'Bis zu 7% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Alkoholische Getränke'],
    },
    {
      name: 'ABOUT YOU',
      about:
        '<p><span style="caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">ABOUT YOU ist ein Fashion Online Store, der in mehr als 20 Ländern aktiv ist. Entdecken Sie unser großes Sortiment mit über 600.000 Produkten von mehr als 3.000 Marken.</span><br style="margin: 0px; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"></p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 4171,
      slug: 'about-you',
      logo: 'https://savebucks.de/img/about-you-de.png',
      banner_image: null,
      homepage: 'https://www.aboutyou.de',
      domain_name: 'aboutyou.de',
      extension_afflink: null,
      cats: ['20', '21', '22', '25'],
      cashback_enabled: 1,
      cashback_amount: '10.50',
      cashback_type: 'cashback',
      cashback_was: 'percent|7.50',
      amount_type: 'percent',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 393,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 892,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-000-0000010.50',
      similar_stores: [],
      cashback_string: 'Bis zu 10.5% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Kleidung & Mode', 'Damen & Herren Bekleidung', 'Schuhe', 'Kinder Kleidung'],
    },
    {
      name: 'aboutfood',
      about:
        '<p><span style="caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Von Pasta und Gewürzen über Cookies und Schokolade bis hin zu Backzutaten und Drinks erwarten die Kunden an jeder Ecke im Online-Shop die leckersten Food-Trends und Fundstücke aus ganz Europa. Viele Produkte sind in exklusiven Vorteilssets erhältlich. Im Sortiment sind tolle Brands wie ManiLife, Tony\'s Chocolonely, 3Bears und Oatsome.&nbsp;</span><br></p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 302,
      slug: 'aboutfood-de',
      logo: 'https://savebucks.de/img/images/partner-logos/50723.png',
      banner_image: null,
      homepage: 'https://www.aboutfood.de',
      domain_name: 'aboutfood.de',
      extension_afflink: null,
      cats: ['14'],
      cashback_enabled: 1,
      cashback_amount: '6.00',
      cashback_type: 'cashback',
      cashback_was: null,
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 28,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 24,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-000-0000006.00',
      similar_stores: [],
      cashback_string: 'Bis zu 6% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Essen & Trinken'],
    },
    {
      name: 'ACE – Auto Club Europa',
      about:
        '<p style="margin-bottom: 0.5rem; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Der Auto Club Europa (ACE) ist mit seinen über 600.000 Mitgliedern der zweitgrößte Automobilclub Deutschlands. Mit mehr als 100.000 Autos, die durch den ACE pro Jahr wieder flott gemacht werden, haben ACE-Mitglieder im Pannenfall immer einen zuverlässigen Partner an Ihrer Seite. Der ACE bietet nicht nur Abschleppdienst, Unfall- und Pannenhilfe: 24 Stunden an 7 Tagen. &nbsp;Unsere Mitglieder erhalten auch zahlreiche Leistungen, die über die klassische Pannenhilfe hinausgehen, wie Rechtsberatung, Unterstützung bei Wildschaden, Rückholung im Krankheitsfall, Mietwagen bei Fahrzeugausfall, Schutz als Fahrer in allen privaten Fahrzeugen, sowie einen Schutzbrief für Fahrrad, E-Bike und Pedelec. Wir sichern die Mobilität unserer Mitglieder ab.</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 3791,
      slug: 'ace-auto-club-europa',
      logo: 'https://savebucks.de/img/ace-auto-club-europa-de.png',
      banner_image: null,
      homepage: 'https://www.ace.de/startseite.html',
      domain_name: 'www.ace.de',
      extension_afflink: null,
      cats: ['36', '40'],
      cashback_enabled: 1,
      cashback_amount: '14.00',
      cashback_type: 'cashback',
      cashback_was: 'fixed|10.00',
      amount_type: 'fixed',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 22,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 30,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-999-0000014.00',
      similar_stores: [],
      cashback_string: 'Bis zu 14,00 € Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Finanzen & Versicherungen', 'Versicherungen'],
    },
    {
      name: 'Acoskincare DE',
      about:
        '<p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">ACO ist die Nr. 1 Hautpflege in schwedischen Apotheken. Natürlich in der Haut vorkommende Wirkstoffe bilden die Basis für sorgfältig zusammengestellte Produkte. Unsere "Scandinavian Composition" - wirkungsvolle Hautpflege, die aus dem skandinavischen Klima heraus geboren ist.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">CLEAN SCANDI BEAUTY</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Als Skandinavier glauben wir an durchdachte Einfachheit und wählen daher ausschließlich Wirkstoffe, die gut für dich und für deine Haut sind. Wirkstoffe, die in Einklang mit deiner Haut arbeiten – sorgfältig ausgewählt, um dich strahlen zu lassen und deine Haut in Bestform zu bringen. Und natürlich Wirkstoffe, die vegan und frei von Tierversuchen sind.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">EFFEKTIVE KOMPOSITIONEN</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Mit mehr als 80 Jahren Erfahrung im Bereich der Hautpflege, wissen wir, wie man Produkte entwickelt, die wirklich funktionieren. Wir glauben an eine Hautpflegeroutine mit wenigen multifunktionalen Produkten, die deine Haut respektieren und dennoch äußerst kraftvoll und effektiv sind. Unkomplizierte Hautpflege - ohne bei der Wirkung Kompromisse einzugehen.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">BASIERT AUF DEM SKANDINAVISCHEN KLIMA</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Wir wissen, dass Feuchtigkeit die Basis für gesunde, strahlende Haut ist. Deshalb haben wir Produkte kreiert, die die Haut tiefenwirksam mit Feuchtigkeit versorgen und helfen, die natürliche Barriere der Haut zu stärken. Maßgeschneidert für das raue skandinavische Klima, schützen ACO\'s Produkte deine Haut zuverlässig vor jahreszeitlich bedingten Einflüssen.</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 181,
      slug: 'acoskincare-de',
      logo: 'https://savebucks.de/img/acoskincare-de.png',
      banner_image: null,
      homepage: 'https://acoskincare.de',
      domain_name: 'acoskincare.de',
      extension_afflink: null,
      cats: ['10', '13'],
      cashback_enabled: 1,
      cashback_amount: '7.50',
      cashback_type: 'cashback',
      cashback_was: 'percent|7.50',
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 23,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 38,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-000-0000007.50',
      similar_stores: [],
      cashback_string: 'Bis zu 7.5% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Beauty & Gesundheit', 'Gesundheit'],
    },
    {
      name: 'Actinovo DE',
      about:
        '<p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Wir revolutionieren den Markt der Nahrungsergänzungsmittel, durch unsere liposomale Technologie, die das Beste aus Natur und Wissenschaft vereint.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Die meisten Nahrungsergänzungsmittel scheitern an der Aufnahme im Darm oder werden sogar vorher schon durch die Verdauungssäfte zerstört.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Nur ein geringer Prozentsatz, je nach Art des Wirkstoffes, kommt am Ende im Blutkreislauf und damit in den Zellen an.&nbsp;</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Bei uns kommen die Wirkstoffe jedoch dank der liposomalen Formulierung am richtigen Ort an, werden um ein Vielfaches besser resorbiert und sind zudem besser verträglich als herkömmlicher Nahrungsergänzung.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Möglich wird das durch unsere innovative LipoSome Technologie, durch die der Aktivstoff in Liposomen eingekapselt wird. Diese bestehen aus Phospholipiden, was gleichzeitig ein Bestandteil der menschlichen Zellmembran ist.&nbsp;</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">So eingekapselt wird der Wirkstoff vor den Verdauungssäften geschützt und wird durch diesen gut maskierten Transport im Darm aufgenommen. Dadurch gelangt der Aktivstoff „per Taxi ins Blut“.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Klinische Studien zeigen, dass die Wirkstoffe durch unserer flüssigen liposomalen Formulierungen eine bis zu 64x höhere Bioverfügbarkeit aufweisen als herkömmliche Nahrungsergänzungsmittel in Tabletten oder Pulverform.</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 174,
      slug: 'actinovo-de',
      logo: 'https://savebucks.de/img/actinovo-de.png',
      banner_image: null,
      homepage: 'https://www.actinovo.com/de',
      domain_name: 'actinovo.com',
      extension_afflink: null,
      cats: ['18'],
      cashback_enabled: 1,
      cashback_amount: '7.00',
      cashback_type: 'cashback',
      cashback_was: 'percent|5.00',
      amount_type: 'percent',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 13,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 22,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-000-0000007.00',
      similar_stores: [],
      cashback_string: 'Bis zu 7% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Nahrungsergänzung'],
    },
    {
      name: 'ACV DE',
      about:
        '<p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><strong style="margin: 0px; padding: 0px;">ACV – Automobil-Club Verkehr</strong></p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Der ACV Automobil-Club Verkehr bietet rund um Europa, im Premium-Tarif sogar weltweit Mobilitätsschutz. Dank unseres Zugriffs auf eine der großen Pannenhilfe-Flotten sind unsere Mitglieder rund um die Uhr sicher und sorgenfrei unterwegs.</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Mit über 500.000 Mitgliedern ist der ACV der drittgrößte Automobilclub in Deutschland. Außerdem sind wir deutschlandweit der einzige Automobilclub, der unabhängig von der gewählten Mitgliedschaft alle Leistungen anbietet – und dabei sind wir noch bis zu 60 € günstiger als die Konkurrenz!</p><p style="padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Die Mobilität unserer Mitglieder zu sichern ist der Grund, warum es uns gibt. Dies wird auch immer der Kern bleiben, doch die Mobilität entwickelt sich weiter und geht schon lange über das eigene Auto hinaus. Als klimafreundlichster Automobilclub Deutschlands werden wir langfristig die Entwicklung zum nachhaltigen Mobilitätsclub vollziehen, denn wir sind überzeugt, dass Mobilität und Nachhaltigkeit zusammengehören.</p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 38,
      slug: 'acv-de',
      logo: 'https://savebucks.de/img/acv-de.png',
      banner_image: null,
      homepage: 'https://www.acv.de',
      domain_name: 'www.acv.de',
      extension_afflink: null,
      cats: ['4', '36'],
      cashback_enabled: 1,
      cashback_amount: '14.00',
      cashback_type: 'cashback',
      cashback_was: 'fixed|10.00',
      amount_type: 'fixed',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 46,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 460,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-999-0000014.00',
      similar_stores: [],
      cashback_string: 'Bis zu 14,00 € Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Auto', 'Finanzen & Versicherungen'],
    },
    {
      name: 'adidas',
      about:
        '<p>Adidas ist eine weltweit führende deutsche Sportmarke, die sich auf die Herstellung von Sportbekleidung, Schuhen und Ausrüstung spezialisiert hat. Gegründet 1949 von Adolf "Adi" Dassler, ist Adidas bekannt für seine ikonischen drei Streifen und das Engagement für innovative Designs und hochwertige Produkte.</p><p>Die Marke bedient eine breite Palette von Sportarten, darunter Fußball, Laufen, Basketball und Tennis, und bietet auch Freizeitmode und Lifestyle-Produkte an. Neben dem Fokus auf Sportler und professionelle Athleten hat Adidas auch erfolgreiche Kooperationen mit Prominenten, Designern und Künstlern gestartet, die die Marke zu einem festen Bestandteil in der Sport- und Modewelt gemacht haben.&nbsp;<br></p><p>Adidas steht für Leistung, Qualität und Stil und hat sich zu einer der größten Sportmarken der Welt entwickelt.<br></p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 4628,
      slug: 'adidas',
      logo: 'https://savebucks.de/img/adidas-de.png',
      banner_image: null,
      homepage: 'https://www.adidas.de',
      domain_name: 'adidas.de',
      extension_afflink: null,
      cats: ['20', '21', '2', '25', '22'],
      cashback_enabled: 1,
      cashback_amount: '4.20',
      cashback_type: 'cashback',
      cashback_was: 'percent|4.20',
      amount_type: 'percent',
      rate_type: 'flat',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 96,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 36,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-000-0000004.20',
      similar_stores: [],
      cashback_string: 'Bis zu 4.2% Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Sport', 'Kleidung & Mode', 'Damen & Herren Bekleidung', 'Schuhe', 'Kinder Kleidung'],
    },
    {
      name: 'AdmiralDirekt',
      about:
        '<p><span style="caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">Wir bieten günstige und leistungsstarke Kfz-Versicherungen an. Bei uns bestimmt nicht einfach nur das Fahrzeug oder die Schadenfreiheitklasse den Beitrag. Unsere Tarife sind wesentlich individueller, weil wir einige wenige Fragen mehr stellen. Dadurch zahlen unsere Kunden bei AdmiralDirekt&nbsp;nur das, was sie auch zahlen müssen. Das finden wir fair.</span><br style="margin: 0px; padding: 0px; caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;"><span style="caret-color: rgb(68, 68, 68); color: rgb(68, 68, 68); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, Tahoma, sans-serif; font-size: 12px;">So ist es nicht verwunderlich, dass uns mittlerweile rund 200.000 Kunden ihr Vertrauen schenken.</span><br></p>',
      terms_todo: '',
      terms_not_todo: '',
      tips: '',
      tracking_speed: '',
      id: 197,
      slug: 'admiraldirekt',
      logo: 'https://savebucks.de/img/admiraldirekt-de.png',
      banner_image: null,
      homepage: 'https://www.admiraldirekt.de',
      domain_name: 'admiraldirekt.de',
      extension_afflink: null,
      cats: ['36', '40'],
      cashback_enabled: 1,
      cashback_amount: '45.50',
      cashback_type: 'cashback',
      cashback_was: 'fixed|32.50',
      amount_type: 'fixed',
      rate_type: 'upto',
      confirm_duration: '90 Days',
      is_claimable: true,
      is_shareable: true,
      is_featured: false,
      country_tenancy: ['DE'],
      is_promoted: false,
      visits: 22,
      offers_count: 0,
      rating: '0.0',
      rating_count: 0,
      clicks: 35,
      ghost: 0,
      filter: null,
      apply_coupon: null,
      checkout_url: null,
      discount: null,
      alpha: 'A',
      cashback_sort: '999-999-0000045.50',
      similar_stores: [],
      cashback_string: 'Bis zu 46,00 € Cashback',
      confirm_days: '09.04.2025',
      boost_percent: null,
      boost_percent_expiry: null,
      categories: ['Finanzen & Versicherungen', 'Versicherungen'],
    },
  ];

  // dummy data remove this once dynamic
  const couponCardData = [
    {
      title: '10% Nachlass bei der Anmeldung zum Newsletter von Hoffmann!',
      description:
        'Melden Sie sich jetzt zum „selbstgemacht mit Calle“- Newsletter an und sichern Sie sich 10% Rabatt auf Ihr erstes Kochgeschirr, leckere Rezepte und Zugang zu exklusiven Angeboten.',
      id: 1159,
      store_id: 42,
      code: null,
      extension_afflink: null,
      is_featured: false,
      start_date: '2022-10-28',
      expiry_date: '2032-11-30',
      store: {
        name: 'Hoffmann-Germany DE',
        id: 42,
        slug: 'hoffmann-germany-de',
        logo: 'https://savebucks.de/img/hoffmann-germany-de.png',
        banner_image: null,
        extension_afflink: null,
        cashback_enabled: 1,
        cashback_amount: '3.15',
        cashback_type: 'cashback',
        cashback_was: 'percent|2.25',
        amount_type: 'percent',
        rate_type: 'flat',
        country_tenancy: ['DE'],
        is_promoted: false,
        offers_count: 1,
        checkout_url: null,
        discount: null,
        alpha: 'H',
        cashback_sort: '999-000-0000003.15',
        cashback_string: 'Bis zu 3.2% Cashback',
        boost_percent: null,
        boost_percent_expiry: null,
        categories: ['Wohnen & Haushalt', 'Haushaltsgeräte'],
      },
    },
    {
      title: '10% Nachlass bei der Anmeldung zum Newsletter von Hoffmann!',
      description:
        'Melden Sie sich jetzt zum „selbstgemacht mit Calle“- Newsletter an und sichern Sie sich 10% Rabatt auf Ihr erstes Kochgeschirr, leckere Rezepte und Zugang zu exklusiven Angeboten.',
      id: 1159,
      store_id: 42,
      code: null,
      extension_afflink: null,
      is_featured: false,
      start_date: '2022-10-28',
      expiry_date: '2032-11-30',
      store: {
        name: 'Hoffmann-Germany DE',
        id: 42,
        slug: 'hoffmann-germany-de',
        logo: 'https://savebucks.de/img/hoffmann-germany-de.png',
        banner_image: null,
        extension_afflink: null,
        cashback_enabled: 1,
        cashback_amount: '3.15',
        cashback_type: 'cashback',
        cashback_was: 'percent|2.25',
        amount_type: 'percent',
        rate_type: 'flat',
        country_tenancy: ['DE'],
        is_promoted: false,
        offers_count: 1,
        checkout_url: null,
        discount: null,
        alpha: 'H',
        cashback_sort: '999-000-0000003.15',
        cashback_string: 'Bis zu 3.2% Cashback',
        boost_percent: null,
        boost_percent_expiry: null,
        categories: ['Wohnen & Haushalt', 'Haushaltsgeräte'],
      },
    },
    {
      title: '10% Nachlass bei der Anmeldung zum Newsletter von Hoffmann!',
      description:
        'Melden Sie sich jetzt zum „selbstgemacht mit Calle“- Newsletter an und sichern Sie sich 10% Rabatt auf Ihr erstes Kochgeschirr, leckere Rezepte und Zugang zu exklusiven Angeboten.',
      id: 1159,
      store_id: 42,
      code: null,
      extension_afflink: null,
      is_featured: false,
      start_date: '2022-10-28',
      expiry_date: '2032-11-30',
      store: {
        name: 'Hoffmann-Germany DE',
        id: 42,
        slug: 'hoffmann-germany-de',
        logo: 'https://savebucks.de/img/hoffmann-germany-de.png',
        banner_image: null,
        extension_afflink: null,
        cashback_enabled: 1,
        cashback_amount: '3.15',
        cashback_type: 'cashback',
        cashback_was: 'percent|2.25',
        amount_type: 'percent',
        rate_type: 'flat',
        country_tenancy: ['DE'],
        is_promoted: false,
        offers_count: 1,
        checkout_url: null,
        discount: null,
        alpha: 'H',
        cashback_sort: '999-000-0000003.15',
        cashback_string: 'Bis zu 3.2% Cashback',
        boost_percent: null,
        boost_percent_expiry: null,
        categories: ['Wohnen & Haushalt', 'Haushaltsgeräte'],
      },
    },
    {
      title: '10% Nachlass bei der Anmeldung zum Newsletter von Hoffmann!',
      description:
        'Melden Sie sich jetzt zum „selbstgemacht mit Calle“- Newsletter an und sichern Sie sich 10% Rabatt auf Ihr erstes Kochgeschirr, leckere Rezepte und Zugang zu exklusiven Angeboten.',
      id: 1159,
      store_id: 42,
      code: null,
      extension_afflink: null,
      is_featured: false,
      start_date: '2022-10-28',
      expiry_date: '2032-11-30',
      store: {
        name: 'Hoffmann-Germany DE',
        id: 42,
        slug: 'hoffmann-germany-de',
        logo: 'https://savebucks.de/img/hoffmann-germany-de.png',
        banner_image: null,
        extension_afflink: null,
        cashback_enabled: 1,
        cashback_amount: '3.15',
        cashback_type: 'cashback',
        cashback_was: 'percent|2.25',
        amount_type: 'percent',
        rate_type: 'flat',
        country_tenancy: ['DE'],
        is_promoted: false,
        offers_count: 1,
        checkout_url: null,
        discount: null,
        alpha: 'H',
        cashback_sort: '999-000-0000003.15',
        cashback_string: 'Bis zu 3.2% Cashback',
        boost_percent: null,
        boost_percent_expiry: null,
        categories: ['Wohnen & Haushalt', 'Haushaltsgeräte'],
      },
    },
    {
      title: '10% Nachlass bei der Anmeldung zum Newsletter von Hoffmann!',
      description:
        'Melden Sie sich jetzt zum „selbstgemacht mit Calle“- Newsletter an und sichern Sie sich 10% Rabatt auf Ihr erstes Kochgeschirr, leckere Rezepte und Zugang zu exklusiven Angeboten.',
      id: 1159,
      store_id: 42,
      code: null,
      extension_afflink: null,
      is_featured: false,
      start_date: '2022-10-28',
      expiry_date: '2032-11-30',
      store: {
        name: 'Hoffmann-Germany DE',
        id: 42,
        slug: 'hoffmann-germany-de',
        logo: 'https://savebucks.de/img/hoffmann-germany-de.png',
        banner_image: null,
        extension_afflink: null,
        cashback_enabled: 1,
        cashback_amount: '3.15',
        cashback_type: 'cashback',
        cashback_was: 'percent|2.25',
        amount_type: 'percent',
        rate_type: 'flat',
        country_tenancy: ['DE'],
        is_promoted: false,
        offers_count: 1,
        checkout_url: null,
        discount: null,
        alpha: 'H',
        cashback_sort: '999-000-0000003.15',
        cashback_string: 'Bis zu 3.2% Cashback',
        boost_percent: null,
        boost_percent_expiry: null,
        categories: ['Wohnen & Haushalt', 'Haushaltsgeräte'],
      },
    },
  ];
  return {
    TickerCountryDropDown,
    EarningSubMenu,
    storeCardData,
    couponCardData,
    deviceFilterOptions,
  };
};

export default useConstant;
