const authUrl = process.env.NEXT_PUBLIC_BASE_API_END_POINT + 'auth';
export const config = {
  default_lang: 'en',
  RECOMMENDED_TASK_NUMBER_TO_FETCH: 8,
  FEATURED_TASK_NUMBER_TO_FETCH: 12,
  FEATURED_STORE_NUMBER_TO_FETCH: 20,
  BASE_API_END_POINT: process.env.NEXT_PUBLIC_BASE_API_END_POINT,
  API_END_POINT: process.env.NEXT_PUBLIC_BASE_API_END_POINT + 'api/v1/',
  LOGIN_END_POINT: authUrl + '/login',
  WEB_URL: process.env.NEXT_PUBLIC_WEB_URL,
  REGISTER_END_POINT: authUrl + '/register',
  PRIVACYPOLICYURL: '/privacy-policy',
  TERMSURL: '/terms',
  ANDROID_KEY: 'android',
  IOS_KEY: 'ios',
  DESKTOP_KEY: 'web',
  REFERRAL_URL: process.env.NEXT_PUBLIC_WEB_URL + 'register',
  COUNTRY_FLAG: 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/svg/:COUNTRY_CODE.svg',
  DEFAULT_CHART_DAYS: 30,
  MOBILE_DEFAULT_CHART_DAYS: 15,
  DEFAULT_TABLE_DATA_LIMIT: 25,
  DEFAULT_DATE_FORMATE: 'DD/MM/YYYY',
  DEFAULT_DATE_FORMATE_WITH_TIME: 'DD/MM/YYYY hh:mm A',
  DEFAULT_CURRENCY_SYMBOL: '₹',
  DEFAULT_CURRENCY: 'INR',
  ONESIGNAL_APP_ID: process.env.NEXT_PUBLIC_ONESIGNAL_APP_ID || 'd6dde05e-aa9d-4e5d-bf2d-c23996ab3546',
  NEXT_AUTH_COOKIE_NAME: 'authjs.session-token',
  SOCIAL_AUTH_COOKIE_NAME: 'token',
  DAILY_LEADERBOARD_CODE: 'daily_leaderboard',
  MONTHLY_LEADERBOARD_CODE: 'monthly_leaderboard',
  TICKER_DATA_UPDATE_INTERVAL: 10000,
  DEFAULT_CURRENCY_FORMATE: 'en-IN',
  WS_URL: process.env.NEXT_PUBLIC_CHAT_WS_URL,
  CURRENCY_SHOW_COOKIE: 'currency-in-points',
  EARN_PAGE_BLOCKS_LIST: ['featured-offers', 'recommended-offers', 'offer-partners', 'survey-partners'],
  IS_MOBILE_COOKIE: 'isMobileApp',
  USE_MOBILE_HOOK_BREAKPOINT: 640, // do not change this breakpoint
  USE_TABLET_HOOK_BREAKPOINT: 1023, // do not change this breakpoint
  AUTH_FORM_STYLE: process.env.NEXT_PUBLIC_AUTH_FORM_STYLE,
  INTERCOM_ID: process.env.NEXT_PUBLIC_INTERCOM_APP_ID,
  OUT_PAGE_REDIRECTION_TIME_IN_MS: 2000,
  GIFT_CARD_PAYOUT_GROUP_NAME: 'Withdraw Giftcards',
  REFERRAL_PARAM: 'referral',
  ROOT_DOMAIN: process.env.NEXT_PUBLIC_ROOT_DOMAIN,
  PLAY_STORE_APP_ID: 'https://play.google.com/store/apps/details?id=com.app.savebucks',
  APPLE_APP_ID: 'https://apps.apple.com/de/app/savebucks-rewards/id6463894642?ign-itscg=30200',
  COUNTRY_COOKIE: 'country_code',
  SHOW_STORES: 'stores',
  CLICK_CODE_COOKIE: 'click_code',
  SOURCE_COOKIE: 'source',
  UTM_SOURCE_COOKIE: 'utm_source',
  PUBLISHER_ID_COOKIE: 'publisher_id',
  TRANSACTION_ID_COOKIE: 'transaction_id',
};
